# Prereqs: Install Ubuntu, apt-get install openssh-server, copy over public key to /root/.ssh/authorized_keys 
# At work need to apt-get install curl to get through proxy, do auth script

# Ansible box needs
#      ansible-galaxy install rvm_io.rvm1-ruby


---

- hosts: vulnreport

  vars:
    vulnreport_install_dir: "/opt/vulnreport"
    ruby_version: "2.1.2"

  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, become: no }

  tasks:
    - name: Update with apt-get update/upgrade
      apt: upgrade=dist update_cache=yes cache_valid_time=3600

    - name: ensure postgresql is at the latest version
      apt: name=postgresql state=latest

    - name: ensure that postgresql is started
      service: name=postgresql state=started

    - name: Install important apps for VulnReport
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - redis-tools
        - bundler
        - wkhtmltopdf
        - python-pip
        - git
        - curl
        - gnupg2
        - postgresql-server-dev-9.3
    - name: Make sure Rollbar Agent is updated
      pip: name=rollbar-agent state=latest

    - name: Install other fun tools
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - tmux
        - tree
        - fail2ban
        - aide
        - psad
        - logwatch

    - name: Download VulnReport from Repo
      git: repo=https://github.com/salesforce/vulnreport.git
           dest={{vulnreport_install_dir}}

    - command: "cp {{vulnreport_install_dir}}/.env.example {{vulnreport_install_dir}}/.env"
      args:
         creates: "{{vulnreport_install_dir}}/.env"
